INPUT:
  PIXEL_MEAN: [0., 0., 0.]
  PIXEL_STD: [1., 1., 1.]

DATALOADER:
  TRAIN:
    BATCH_SIZE: 128

OPTIM:
  LR: 0.05
  MAX_EPOCH: 50
  LR_SCHEDULER: "single_step"
  STEP_SIZE: 20

TRAINER:
  DDAIG:
    G_ARCH: "fcn_3x32_gctx"
    LMDA: 0.3